apiVersion: v1
kind: Service
metadata:
  name: hermes-gateway-1
  namespace: hermes-agent
spec:
  type: ClusterIP
  ports:
    - name: webui
      port: 6060
      protocol: TCP
      targetPort: 6060
    - name: gateway-api
      port: 8642
      protocol: TCP
      targetPort: 8642
  selector:
    app: hermes-gateway-1
